language: node_js
node_js:
  - 12.18.3
before_script:
  - cd website
  - npm install
  - cd ..
  - cd mobile-app
  - npm install
  - cd ..
script: 
  - cd mobile-app
  - npm run test-ci
  - cd ..
  - cd website
  - npm run test-ci